steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/jmn-journal/web:$SHORT_SHA', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/jmn-journal/web:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/jmn-journal/web:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/jmn-journal/web:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'jmn-journal', '--image', 'asia-south1-docker.pkg.dev/$PROJECT_ID/jmn-journal/web:$SHORT_SHA', '--region', 'asia-south1', '--platform', 'managed', '--allow-unauthenticated', '--port', '8080', '--min-instances', '1', '--max-instances', '10', '--memory', '512Mi']
images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/jmn-journal/web:$SHORT_SHA'
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/jmn-journal/web:latest'
